<div id="pre-inspection-view-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/75 px-4 py-6" aria-hidden="true">
    <div class="dashboard-scroll max-h-[calc(100vh-2.5rem)] w-full overflow-y-auto rounded-lg border border-fleet-line bg-fleet-surface shadow-2xl" style="max-width: 760px;" role="dialog" aria-modal="true" aria-labelledby="pre-inspection-view-modal-title">
        <div class="p-6" data-pre-inspection-detail-sheet>
            <div class="mb-6 flex items-start justify-between gap-4"><div><p class="text-xs font-extrabold uppercase tracking-[0.18em] text-fleet-primary">Pre-Inspection Details</p><h2 id="pre-inspection-view-modal-title" class="mt-2 text-2xl font-extrabold text-fleet-ink" data-pre-inspection-view-title>Pre-inspection report</h2><p class="mt-1 text-sm text-fleet-muted" data-pre-inspection-view-subtitle>Full pre-inspection information for the selected report.</p></div><button type="button" data-close-pre-inspection-view-modal class="flex h-8 w-8 items-center justify-center rounded-lg text-2xl leading-none text-fleet-muted hover:bg-fleet-surface-muted hover:text-fleet-ink" aria-label="Close pre-inspection details">&times;</button></div>
            <div class="grid gap-5 md:grid-cols-2">
                <div class="rounded-2xl border border-fleet-line bg-white p-5"><p class="text-xs font-extrabold uppercase tracking-[0.18em] text-fleet-muted">Report Overview</p><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Invoice No.</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-invoice>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Date</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-date>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Vehicle</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-vehicle>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Make / Model</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-make-model>-</dd></div></dl></div>
                <div class="rounded-2xl border border-fleet-line bg-white p-5"><p class="text-xs font-extrabold uppercase tracking-[0.18em] text-fleet-muted">Inspection Status</p><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Inspector</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-inspector>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Title</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-inspector-title>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Mileage</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-mileage>-</dd></div><div class="flex justify-between gap-4"><dt class="text-fleet-muted">Overall Status</dt><dd class="font-semibold text-fleet-ink" data-pre-inspection-view-overall>-</dd></div></dl></div>
                <div class="rounded-2xl border border-fleet-line bg-white p-5 md:col-span-2"><p class="text-xs font-extrabold uppercase tracking-[0.18em] text-fleet-muted">Defects Summary</p><p class="mt-4 text-sm leading-6 text-fleet-ink" data-pre-inspection-view-defects>-</p></div>
            </div>
            <div class="mt-6 flex justify-end gap-3 border-t border-fleet-line-soft pt-5"><button type="button" data-print-pre-inspection-view class="inline-flex h-10 items-center gap-2 rounded-lg border border-fleet-line bg-fleet-surface px-4 text-sm font-semibold text-fleet-ink shadow-sm hover:bg-fleet-surface-muted"><span>P</span><span>Print Report Details</span></button><button type="button" data-close-pre-inspection-view-modal class="h-10 rounded-lg bg-fleet-sidebar px-4 text-sm font-semibold text-white shadow-sm hover:bg-fleet-sidebar-active">Close</button></div>
        </div>
    </div>
</div>
